name: CI

on:
  push:
    branches:
      - master
      - next
      - 'v*'
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  node12:
    name: Node 12.x
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn test

  nodeX:
    name: Node ${{ matrix.node-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10

    needs: [node12]

    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [10.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - run: yarn test

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: [node12]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x

      - name: install dependencies
        run: yarn install --no-lockfile

      - run: yarn test
